# Generated by Django 2.2.13 on 2022-02-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, default='', max_length=128)),
                ('ip', models.GenericIPAddressField(db_index=True, default='0.0.0.0')),
                ('mac', models.CharField(default='', max_length=32)),
                ('os', models.CharField(default='', max_length=64)),
                ('arch', models.CharField(default='', max_length=16)),
                ('mem', models.BigIntegerField(default=0)),
                ('cpu_model', models.CharField(default='', max_length=64)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('disk', models.CharField(default='{}', max_length=512)),
                ('sn', models.CharField(default='', max_length=128)),
                ('user', models.CharField(default='', max_length=128)),
                ('remark', models.TextField(default='')),
                ('purchase_time', models.DateTimeField()),
                ('over_insurance_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_time', models.DateTimeField()),
            ],
        ),
    ]
