# Generated by Django 2.2.13 on 2022-02-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='cpu_cores',
            new_name='cpu',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu_model',
        ),
    ]
