# Generated by Django 2.2.13 on 2022-02-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20220212_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_usage',
            field=models.FloatField(default=0.0),
        ),
    ]
