# Generated by Django 2.2.13 on 2022-02-23 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20220217_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='os',
        ),
        migrations.RemoveField(
            model_name='host',
            name='over_insurance_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='purchase_time',
        ),
        migrations.RemoveField(
            model_name='host',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_time',
        ),
        migrations.AddField(
            model_name='host',
            name='application',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='host',
            name='heartbeat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='host',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='host',
            name='platform',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='position',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='host',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, default='0.0.0.0', unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='mac',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='host',
            name='remark',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.CharField(default='', max_length=256),
        ),
    ]
