# Generated by Django 2.2.13 on 2022-02-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=32, unique=True)),
                ('password', models.CharField(default='', max_length=32)),
                ('age', models.IntegerField(default=1)),
                ('sex', models.BooleanField(default=True)),
                ('tel', models.CharField(default='', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
